# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44cf0ade81f0a77a8fae66295f56661ed3b68c30b7e5133a2362ddec6f48873c6c785f10b1bb2189dfb049d801fe98ba8daf795830ec75ff48f8146ae9317760

test:
  secret_key_base: d3b9b9fa7716f671bdbb9e7bfc2200b32e4fb921ed136933ec2b1f1ed9f0e7071036a35d77ceddc13b22b67146aa502ed0fd3f49127079299cf4d52a066c9751

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
